CREATE TABLE USERS
(
	Id VARCHAR(255) NOT NULL PRIMARY KEY,
	Username VARCHAR(50) NOT NULL,
	Password VARCHAR(255) NOT NULL,
	Name VARCHAR(400) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	Salt VARCHAR(50) NOT NULL,
	Token VARCHAR(255) NOT NULL,
	RefreshToken VARCHAR(255) NOT NULL,
	Created DATETIME NOT NULL DEFAULT GETUTCDATE(),
	Modified DATETIME NOT NULL DEFAULT GETUTCDATE(),
	TokenExpiration DATETIME NOT NULL,
	RefreshTokenExpiration DATETIME NOT NULL
)

